# Run zeta0
# This will run the basic zeta0 program, letting you input an n
zeta0: serialzeta.cpp
	g++ serialzeta.cpp -o zeta0
	./zeta0

# Run utest
# This will run the utest for basic zeta0
utest: unittestzeta.cpp
	g++ unittestzeta.cpp -o utestzeta0
	./utestzeta0

# Run vtest
# This will run the vtest for basic zeta0, outputing a txt file
vtest: verificationzeta.cpp
	g++ verificationzeta.cpp -o vtestzeta0
	./vtestzeta0
