# Run mach0
mach0: mach0.c
	gcc mach0.c -o mach0 -lm
	./mach0

# Run utest
utest: utestmach.c
	gcc utestmach.c -o utestmach -lm
	./utestmach

# Run vtest
vtest: vtestmach.c
	gcc vtestmach.c -o vtestmach -lm
	./vtestmach
